### ISSUE TITLE
Update footer bottom GDG icon

### ISSUE THREAD

**Issue by sergiofraile** [GDGCloudDublin/devfest-site#24]
![Annotation 2019-10-20 211703](https://user-images.githubusercontent.com/1710465/67165601-fe562c80-f37e-11e9-9fc4-b37845f71160.jpg)

@laurauzcategui podemos conseguir uno asi para GDG Dublin? No se si puedes editarlo con ilustrator.
El svg que estan usando esta en la carpeta de imagenes, se llama organizer-logo.svg

**Comment by laurauzcategui** [comment]
Ya me lo veo
